### ISSUE TITLE
Alternative format for the chapter file and the internal link.

### ISSUE THREAD

**Issue by An-qi-Zhang** [kuchejak/obsidian-bible-linker-plugin#1]
Thank you so, so much for making this plugin! I have been copy, paste and clean the verses manually for a long time. Thank you for your excellent work for the glory of God!

I would like to suggest, if possible, supports for more formats of the chapter files and the internal links. For example:
- File name: Gen1 (without space)
- Verse range: 1-4
- Verse number: 1, 2, 3, 4
- Internal link:
[[Gen1#1|Gen1:1]][[Gen1#4|-4]]
OR [[Gen1#1|Gen 1:1]][[Gen1#4|-4]]
(Then both the beginning verse and the ending verse can be clicked.)
(If only 1 verse is quoted, [[Gen1#1|Gen1:1]] OR [[Gen1#1|Gen 1:1]])
- Starting symbol:
unordered list "-"
OR blockquote ">"

**Comment by kuchejak** [comment]
Hi, thank you for your kind words, I'm happy you find this plugin usefull.

As for your suggestions:
- Support for filenames without spaces -  I will add it sometime this week. 
- Verse range - already implemented, I hope it works 😅
- Verse numbers - If I understand it properly, you would like to link multiple verses with something like "Gen 1,4.5.6"? That is doable, I just don't know if I will have time to implement this any time soon.
- Adding clickable link to the last verse as well - This is a cool idea and should be relatively easy, so maybe sometime this week as well.
- Starting symbol - I think that for the unordered lists it would be easier to insert the "-" symbol manually and then add link without any leading symbol (btw. the ">" can be used in unorder lists as well). I may add the option to change/remove the leading symbol later. Would you prefer global setting for this, or option to change it in the modal window every time you run the link command?

**Comment by An-qi-Zhang** [comment]
Thank you for your immediate comment!

Sorry for my lack of clarity regarding the verse range and verse numbers. I was setting up the example by repeating the format you are already using and the function you have accomplished. I just changed my file "Gen1" temporarily to "Gen 1". The range format works perfectly! I suggest the "4.5.6" format is not as urgent to be prioritized at the moment.

I appreciate and agree with your preference on the leading symbol. I would like a global setting to type the leading symbol more, with the empty string "" representing no leading symbol. In this way, users who need to change this symbol often, can simply type manually every time. Furthermore, unordered and ordered lists will automatically populate the symbol after pressing "Enter".

A summary for the potential changes:
- Support filenames without spaces.
- Add a clickable link to the last verse, if more than 1 verse is quoted.
- Add a global setting for the leading symbol/string.

Blessings!

**Comment by kuchejak** [comment]
All three features added to version 1.0.1 (update plugin in Settings/Community plugins)

Just a small note - link to last verse is a bit messy in source mode, so I made setting to turn it on/off. Default is off so you will need to change it in the plugin settings (Settings/Bible Linker)
