### ISSUE TITLE
Move verse link out of verse body

### ISSUE THREAD

**Issue by anthonysciutto** [kuchejak/obsidian-bible-linker-plugin#11]
Thank you so much for this plugin -- this is exactly what I looking for and am so glad I stumbled upon it!

I would like to make a feature request: 

Can you add an option to move the verse link out of the verse body and give options for prefix?

**As an example, the current insert looks like this:**
>Gen 1:1-2 **1** In the beginning, God created the heavens and the earth. **2** The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters.  

**I would like it do this:**
##### Gen 1:1-2
>**1** In the beginning, God created the heavens and the earth. **2** The earth was without form and void, and darkness was over the face of the deep. And the Spirit of God was hovering over the face of the waters.  

Prior to this I would use 5th level header for my verse references and then manually type the ![[verse]] under it. I would like to replicate that look but using your plugin.

I tried poking around the .js but I'm woefully underequipped

**Comment by kuchejak** [comment]
Hi, I feel like the plugin settings are becoming a little bit too complicated (with so many options available), so I would prefer to enhance some of the existing settings to get to your desired output (I just have to think about how to acomplish that 😁) or at least create a setting that can be understood easily and used for more purposes (maybe link postfix, where you could put new line?). 

Do you need all the verses on the same line, or it does not matter?

---

> I tried poking around the .js but I'm woefully underequipped

The plugin is actually writen in TypeScript (.ts files) and then compiled to JavaScript (so the .js file is just for the computer, not really for humans to understand/edit). TypeScript sourcecodes are [here](https://github.com/kuchejak/obsidian-bible-linker-plugin/tree/main/src).

**Comment by anthonysciutto** [comment]
Not a need, but I do like the look of them all on one line. 

I think a link postfix would be great. nl + > is exactly what I'm looking for to match the appearance

**Comment by kuchejak** [comment]
Ok, so postfix it is. I will add it during the weekend.

**Comment by kuchejak** [comment]
The main problem with this feature is that I would have to create custom input for the dictionary in the settings, which is probably possible, but I don't have much experience with that so it would probably take some time. 

And well, would you be willing to type in 66 entries for all the Bible books to create the dictionary? I think that most users would be too lazy to do that 😄

**Comment by anthonysciutto** [comment]
You make a compelling argument haha

**Comment by kuchejak** [comment]
Postfix setting added (version 1.2.6), you shoud be able to update now
