### ISSUE TITLE
Request - Make References to Multiple Chapters Too (Not Only Verses)

### ISSUE THREAD

**Issue by RodWarrior** [kuchejak/obsidian-bible-linker-plugin#12]
First of all, I love this plugin. It really helps when i want to input multiple versicles like Psalm 119:1-4. And it evens allows me to do it in the way i write in portuguese, Sl 119:1-4, and it returns:

[[Sl 119#1]]
[[Sl 119#2]]
[[Sl 119#3]]
[[Sl 119#4]]

So i love it.

I would love if it have a feature so i can also input "Sl 1-5" or "Sl 1-5:" to get:

[[Sl 1]]
[[Sl 2]]
[[Sl 3]]
[[Sl 4]]
[[Sl 5]]

Hope this can be done. Thanks!

**Comment by kuchejak** [comment]
Hi, I'm glad that you like the plugin!

Your request seems reasonable, I'm just not sure when will I have spare time to implement it.

**Comment by RodWarrior** [comment]
Thanks. It would be specially helpful in organizing indexes and Maps of Content for bible study. 😀 
Hope it's not that hard and time consuming.

**Comment by kuchejak** [comment]
Added to version 1.2.7, you should be able to update the plugin now

**Comment by RodWarrior** [comment]
Thank you so much. It's perfect and so easy!
