### ISSUE TITLE
Problem with Plug-In

### ISSUE THREAD

**Issue by MickToews** [kuchejak/obsidian-bible-linker-plugin#14]
Hello @kuchejak , first of all, thank you for providing this plug-in. I looked for this functionality.

Sadly, it does not work. 
My Questions: 
Is there a specific folder structure required? I use the [Obsidian bible study kit](https://forum.obsidian.md/t/bible-study-in-obsidian-kit-including-the-bible-in-markdown/12503), but changed the folder structure. 

Maybe I use the wrong Input. I write: ![[Matt-01#v1|Matt-01,1-3]], but there is only the first Vers shown.

Could you support?

Kind regards
Mick

**Comment by kuchejak** [comment]
Hi, it should work with the Obsidian bible study kit just fine, but I think you are using it wrong. You have to use the commands provided by the plugin - press Ctrl+P and type in "Bible linker", then select the command you want to use. If there is a problem with the output try looking into the plugin settings.

**Comment by MickToews** [comment]
@kuchejak Thank you! It works great.
