### ISSUE TITLE
iOS mobile shortcut icon '?'

### ISSUE THREAD

**Issue by Oblique82** [kuchejak/obsidian-bible-linker-plugin#15]
Hi

I would like to suggest a plug-in icon for mobile users so I can recognise it quickly 

on the quickbar on mobile the icon is a '?'

**Comment by Oblique82** [comment]
here is the image https://www.dropbox.com/s/4mtovfew7ioa74a/IMG_5268.PNG?dl=0

**Comment by Oblique82** [comment]
Thanks for trying

I wonder how are other plugins able to achieve it?

- Tim

**Comment by Oblique82** [comment]
Hi, quite a bit has happened since this issue was last reviewed including version 1.0 of obsidian. Is there any chance we can have another look at this? I know it's small, but it really bugs me on my iPad.

**Comment by kuchejak** [comment]
Hi, I'll try. Can you send me a link to a plugin, that has it working?

**Comment by Oblique82** [comment]
thanks for your reply

yes - "task collector" has these icons customised for iOS - different type of stars: https://github.com/ebullient/obsidian-task-collector 

I also note "advanced tables" does for some actions (but not all!)  https://github.com/tgrosinger/advanced-tables-obsidian

**Comment by kuchejak** [comment]
New icons added (version 1.4.4)
