### ISSUE TITLE
Suggestion: invisible links alias verse prefixes

### ISSUE THREAD

**Issue by Oblique82** [kuchejak/obsidian-bible-linker-plugin#16]
I like the invisible links - I wonder if a good option would be - instead of making them invisible (only seen in edit mode), we make the option for the **{n}** prefix to alias the wiki link to each verse

See: https://www.dropbox.com/s/zuae40zqkt65iun/Screenshot%202022-08-18%20at%209.49.49%20am.png?dl=0

**Comment by kuchejak** [comment]
You can now insert {f} for file name, so for links simply use something like [[{f}#{n}]] as prefix.

**Comment by Oblique82** [comment]
thanks I like this update. if we want to hide the bpook/chapter and just have the verse we should be able to do something like:

[[{f}#{n}|**{n}**]] 

however the second verse number doesn't parse

**Comment by kuchejak** [comment]
Fixed

**Comment by Oblique82** [comment]
Thanks great work!

- Tim
