### ISSUE TITLE
Configurable number of space inserted between verses

### ISSUE THREAD

**Issue by ickc** [kuchejak/obsidian-bible-linker-plugin#17]
It seems that currently, a single space is always placed between verses when importing multiple verses. The proposal is to make this configurable (to insert no space.)

This is useful if the source already has the necessary space baked in, or when the language does not expect space between them, such as Chinese.

**Comment by kuchejak** [comment]
Hi, I actually did not know that there are languages that does not use spaces, cool! I added option to disable the spaces to version 1.2.11, you shoud be able to update now.
