### ISSUE TITLE
Specific Reference: "Song of Solomon" Capitalisation Substituted

### ISSUE THREAD

**Issue by Oblique82** [kuchejak/obsidian-bible-linker-plugin#18]
Hi

I note in all my source markdown files "Song of Solomon" has "solomon" capitalised but not when I try to insert the reference using this plugin

See attached

<img width="981" alt="Screen Shot 2022-09-05 at 7 57 22 am" src="https://user-images.githubusercontent.com/98437638/188335853-e2334eb1-f510-4424-9abd-80e4abacf42e.png">

**Comment by kuchejak** [comment]
Copy command will now (v1.3.2) use original filenames for aliases (except for OBSK filenames),
