### ISSUE TITLE
"Create Obsidian Links to Bible Verses" does not like to my verses accurately

### ISSUE THREAD

**Issue by cjolson** [kuchejak/obsidian-bible-linker-plugin#19]
When I use the **Copy Bible Verses** action, it accommodates my file formats for the individual verses by adding the `-` in the file tile and including the `v` prefix for verses.

```
[[Gn-01#v1|Gn 1:1-2]] 
In the beginning God created the heavens and the earth. 
The earth was without form and void, and darkness was upon the face of the deep; and the Spirit of God was moving over the face of the waters. 
[[Gn-01#v1|]][[Gn-01#v2|]]
```

However, when I use the **Create Obsidian Links to Bible Verses** action, it does not:

```
[[Gn 1#1]]
[[Gn 1#2]]
```

You'll notice the difference between `[[Gn-01#v1|]]` and `[[Gn 1#1]]`. 
- It doesn't add the `-` in between the books and the chapter
- It doesn't add the `v` as a prefix for the verse (this one I can fix by using `#v` as my Link Separator, but it's weird that it behaves differently than the invisible link for the Copy Bible Verses action)

**Comment by kuchejak** [comment]
The two commands actually work very differently, so there are some differences like this one. The copy command looks into the files and can get some additional information from them (like the 'v' verse prefix). The link command, on the other hand, is a very simple text parser that does not work with the file content at all — I made this command primarily for people who are unable to use the Copy command.

The automatic usage of '-' could be added to the linking command as well, but I want to first add support for multiple Bible translations to the Copy command.

**Comment by kuchejak** [comment]
Hi, I have looked into the code and it seems to me that this small improvement would take more time to implement than I would like to spend on it. I believe that the link command serves its purpose for people who are unable to use the copy command, and I don't plan to add more features to it (at least for now).

If the '-' character in filenames is causing you problems, I recommend removing it. I'm sure you can find some free tools for renaming multiple files at once.
