### ISSUE TITLE
Multiple Translations doesn't work as designed

### ISSUE THREAD

**Issue by lexiconwriter** [kuchejak/obsidian-bible-linker-plugin#24]
My settings set two bibles in these folders:

Bibel/GNT
Bibel/NWT

![grafik](https://user-images.githubusercontent.com/5838099/209996440-e9a900b8-38e5-42f1-ac4a-1b9338fb7522.png)

For testing reasons the GNT files are duplicated from NWT. 

So in both bibles the the Gen 1:1 starts in this German text as:  

```
# 1Mo 1

### 1
Am Anfang erschuf Gott Himmel und Erde.

### 2
Die Erde nun war formlos und öde. Über dem tiefen Wasser war Dunkelheit und Gottes aktive Kraft bewegte sich über der Wasseroberfläche hin und her.
```

The pathes are like this:

```
C:\Users\Oliver\Documents\Lernen\obsidian\zettelkasten\private\80-Religion\Bibel\GNT
C:\Users\Oliver\Documents\Lernen\obsidian\zettelkasten\private\80-Religion\Bibel\NWT
```

I use the dialog as below:

![grafik](https://user-images.githubusercontent.com/5838099/209996812-7dd578e2-a60a-4f62-b826-e3dcca714a72.png)

I can click between the two translation but will always see the same link. What's wrong?

(Using Windows 11 / Obsidian 1.1.9 / Bible Linker 1.4.3)

**Comment by kuchejak** [comment]
Hi, you have to specify full path from the root folder of your valut. If your root folder is `zettelkasten`, the path should be `private/80-religion/Bibel/GNT/`. The instructions shoud probably explicitly mention this 🤔

Let me know if it helps.

**Comment by lexiconwriter** [comment]
@kuchejak Yes, you are right. Now it works. "Input full path" should be read carefully. But because "Bibel/GNT" and "Bibel/NWT" worked in some way (as single translation) I ignored it. Sorry, my fault.

**Comment by lexiconwriter** [comment]
btw: The German "Gute Nachricht"-Bible uses Gen 2,8-9 as one single verse:

![image](https://user-images.githubusercontent.com/5838099/210093926-22bc9ee5-615c-416b-9f77-86d62d5b4372.png)

Is there a syntax for this exception?

**Comment by kuchejak** [comment]
No, there is no syntax for it; if you want to use multiple translations, their format should be the same for the best experience.
