### ISSUE TITLE
[Feature/Enhancement Requests] Fuzzy Search when link

### ISSUE THREAD

**Issue by potatochick2020** [kuchejak/obsidian-bible-linker-plugin#28]
When linking a verse, e.g. `1Co 1:1`  ,
Typing `1Co` is the only way to link the verse.
It will be better to enable fuzzy search so typing `1Co 1:1` , `1COR 1:1`

# Proposal 
I understand the current logic is doing so by search the exact file name, I think this can be done by adding a "Dictonary" in setting, which allows users to make their mapping for text, e.g. 

| User Input  | Generated text use for search |
|---|---|
| 1Cor | 1CO  | 
| 1corinthians  |1CO   | 

I think this will help alot especially when users use multiple language version of Bible

I could try to do the coding and submit a pull request if you like this feature.

**Comment by kuchejak** [comment]
I have added the option to the settings. Update to version 1.5.1 to use it.
