### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MickToews** [kuchejak/obsidian-bible-linker-plugin#30]
Hello, thank you very much for the wonderful plugin. I have one wish that would make the tool even more valuable to me: Would it be possible that when quoting biblical passages, you could omit comments that are between: %% ... %%. 
Here is an example from Ezekiel 29:18-19:

###### v18
"Son of man, Nebuchadnezzar king of Babylon has made his army work hard against Tyre, so that everyone's heads are bald and everyone's shoulders<sup title="or: backs">&#x2732;</sup> are rubbed raw, but no reward has come to him or to his army of Tyre for the work he has done against the city<sup title="or: for the sake of the city">&#x2732;</sup>."
%% "Son [[H1121]] of man, [[H120]] Nebuchadnezzar [[H5019]], king [[H4428]] of Babylon [[H894]], sent his army [[H2428]] with all his might [[H5647]] against [[H413]] Tyre. [[H6865]] Each [[H3605]] Head [[H7218]] was bald [[H7139]] and every [[H3605]] Shoulder [[H3802]] was made raw. [[H4803]] But he and his army [[H2428]] had [[H1961]] no [[H3808]] pay [[H7939]] from Tyre [[H6865]] for [[H5921]] the labor [[H5656]] they had spent [[H5647]] on it. [[H5921]]

#Ezekiel/Son of man #Geography_Israel/City/Tyrus %%

###### v19
Therefore this is what the LORD God has said: "I will now give the land of Egypt to Nebuchadnezzar king of Babylon, so that he may take its wealth and plunder and plunder it, and this will be his army's reward.
%% Therefore [[H3651]] this is what [[H3541]] the Lord [[H136]] GOD [[H3069]] says: [[H559]] "I will [[H5414]] the land of [[H776]] Egypt [[H4714]] to Nebuchadnezzar [[H5019]], king [[H4428]] of Babylon, [[H894]] who will steal its wealth [[H5375]], [[H1995]] seize its plunder [[H7997]], [[H7998]] and [[H962]] take away its spoil. [[H957]] This will be [[H1961]] the reward [[H7939]] for his army. [[H2426]] %%

__

It would be very helpful if the %% ... %% comments from me could be omitted.

**Comment by kuchejak** [comment]
Hi, thank you for the suggestion. I think that this should be fairly easy to implement and may be useful for more people (maybe if I allow them to set their own comment sequence), so I may look into it over Christmas.

**Comment by kuchejak** [comment]
Hello, I have added support for comments (see the plugin's settings). You should now be able to update the plugin to version 1.4.8 and use it.

As for your second suggestion - you should be able to accomplish that with the _Each verse prefix_ setting.
