### ISSUE TITLE
wrong verse is returned

### ISSUE THREAD

**Issue by swuphoto** [kuchejak/obsidian-bible-linker-plugin#31]
![image](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/1753588/eff43257-3804-4f9d-998e-efc39ee55944)

The above issue occurred several times, I must paste 19#12 in order to get the text of 19#14.

**Comment by kuchejak** [comment]
Hello, try changing the value of "Verse offset" in the plugin settings:
![image](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/94016085/a9c6527d-221b-46de-a2da-09f924ed097f)
