### ISSUE TITLE
FR: Add a Prefix before the first link

### ISSUE THREAD

**Issue by GovSat1** [kuchejak/obsidian-bible-linker-plugin#32]
It would be useful to have a feature to insert custom Prefix before the first link only (or possibly with options to prefix the link or maybe the entire passage).

This is nice for callouts where you would want the text to look like, for example:

```
> [!scripture]+ Gen:1:1-2
> v1.. 
> v2..
```

As it is the only option currently is to prefix every line, including the link. So we can achieve the `> ` prior to every verse but still have to manually add out the callout type.

(FYI, callout is very useful in this instance as you can custom style css the "scripture" type with more appropriate font, and the foldable nature makes it easier to insert scriptures without breaking the flow of notes)

**Comment by kuchejak** [comment]
Hello, I have added this option to the plugin's settings; you should now be able to update the plugin to version 1.4.8 and use it (it is only available when the option _Put each verse on a new line?_ is set to true).

**Comment by kuchejak** [comment]
Makes sense, I'll try to add it soon.

**Comment by kuchejak** [comment]
Added in version 1.4.9. The first line prefix won't be used when the "Link only" option is used.
