### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Hermann-85** [kuchejak/obsidian-bible-linker-plugin#34]
Hello Jakub, 
I don't know how to contact you. But I just wanted to say thank you for the great plugin. I use it so often for my notes and sermon prep. The latest updates are great! May the Lord bless you for your work!

Greetings from Germany
Hermann

**Comment by kuchejak** [comment]
Thank you very much, it's really nice of you! I'm glad that the plugin is helping.
