### ISSUE TITLE
Mix invisible and visible links for longer passages

### ISSUE THREAD

**Issue by tylermrolfe** [kuchejak/obsidian-bible-linker-plugin#36]
First, I'm so grateful to you for this plugin! I'm in seminary and it's **incredibly** helpful!

I'm running into an issue where I want to take a general note on say Job 9:32-35 and what I'd like is the first verse to be visible and the last verse to use "Job 9#35|-35" So that the the middle verses are invisible, but the beginning and end verses are visible making the final structure something like "Job 9#32-35". I hope that makes sense! It's possible to do this manually but a bit tedious...It would be incredible for a setting to toggle on to accomplish this by default.

Is there any way to buy you a cup of coffee or five?! God bless.

**Comment by kuchejak** [comment]
Hello, I'm happy you find the plugin helpful!

As for your feature request, I'm not sure I understand the described feature; could you please send me an example input and desired output? Thank you

btw. I don't have a Patreon or anything similar, so don't worry about buying me a coffee (but I appreciate the idea, thank you!).

**Comment by tylermrolfe** [comment]
No problem! If I type in the prompt "Job 9:32-35" the output with invisible links would be this:
`[[Job 9#32|]][[Job 9#33|]][[Job 9#34|]][[Job 9#35|]]`

but I'd like some way for this format:
`[[Job 9#32]][[Job 9#33|]][[Job 9#34|]][[Job 9#35|-35]]`

Note the removal of the pipe in the first verse making it visible and the change in the last verse. This renders the entire string "Job 9#32-35". I've attached screenshots below to show this. I hope that makes sense!

![Screenshot 2024-02-09 at 9 37 40 AM](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/1797243/7e5ddcb1-b98a-4b48-97f8-4740dfee337e)
![Screenshot 2024-02-09 at 9 37 33 AM](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/1797243/3b204768-8077-457f-9489-8d7238e84842)

**Comment by kuchejak** [comment]
Ok, makes sense. And just to be sure, you are using the link command for this, right? (not the copy command)

**Comment by kuchejak** [comment]
I've implemented it for the link command, you should now be able to update the plugin to version 1.5.0 and use it.

**Comment by tylermrolfe** [comment]
This is AMAZING! Just tried it out and it works great. Thank you thank you!!
