### ISSUE TITLE
Question on using with verses with footnotes included

### ISSUE THREAD

**Issue by Rayquaza1090** [kuchejak/obsidian-bible-linker-plugin#37]
Hello,

Thank you for making such a handy tool at linking the Bible with Obsidian! It's been very useful and I have been greatly enjoying the plugin so far.

I had a quick question about the possibility of editing verses or making it automatically detecting footnotes. 

For me, this is how Genesis 1.1 appears with my Bible by default

![footnote1](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/46958809/958f47fc-536a-4c2d-a5b2-68e52bc0a0ae)

And this is how it looks when I reference that line using the Bible Linker

![footnote2](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/46958809/b27c69e5-fe6c-4c60-ada5-618a729d3028)

Maybe I'm missing it already, but is there some feature in the plugin already that would allow me to work around it? Or is there some other way bar removing them entirely that I would have to do to make it work?

Thanks a ton, keep doing God's work!

**Comment by kuchejak** [comment]
Hello, I'm glad you like the plugin!
It looks like you are using the "Link Bible verses" command which only generates the links that are then used by Obsidian. In you example you are using the embedding notation `![[link]]` and Obsidian is handling how it is displayed (see Obsidian docs [here](https://help.obsidian.md/Linking+notes+and+files/Embed+files)). I personally don't use footnotes, but it looks like they are not supported when embedding a note, as you have already discovered yourself. It is possible that the Obsidian team will implement this in the future, see [this](https://forum.obsidian.md/t/make-footnotes-in-embedded-pages-work/18832) feature request.

One alternative would be to use the "Copy and Link Bible verses" which copies the text itself and lets you modify it in the process. If you don't need the footnotes to be copied, you can mark them as comments and the plugin will automatically skip them.

<img width="775" alt="image" src="https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/94016085/0b0ad724-f784-430f-9180-878f0bc7f0a2">

Hope this helps

**Comment by Rayquaza1090** [comment]
Kuchejak,

I'm sorry for the late response. When I was originally beginning to work with Obsidian, I was greatly overwhelmed by the sheer scale of the project I had in mind, and was having difficulty downloading the Bible version I was seeking.

I have managed to get going for the most part, but I wanted to thank you for taking the time to respond. This plugin has been indescribably helpful, and I look forward to using it extensively in the future.

Happy Easter!
