### ISSUE TITLE
Linking in Canvas

### ISSUE THREAD

**Issue by der-bingle** [kuchejak/obsidian-bible-linker-plugin#38]
Since I started doing sermon prep in Obsidian, your plugin is absolutely essential, so first of all, thank you for the hard work of not only writing, but maintaining it!

At the center of my workflow is a canvas where I collect/link/brainstorm everything related to the sermon. **It would be so helpful if the Bible Linker modal  worked on canvases.** Right now, I have to keep another tab open with a regular note just to copy/link a Scripture so that I can cut and paste it onto the canvas.

**Comment by kuchejak** [comment]
Hello, I might look into this some day. I don't know why Obsidian doesn't automatically make the modals work on canvases, but maybe there is a way to make that work.

**Comment by kuchejak** [comment]
It should now work (version 1.5.5)
