### ISSUE TITLE
Linking a different Language

### ISSUE THREAD

**Issue by SimonZindo** [kuchejak/obsidian-bible-linker-plugin#39]
Greetings, I would first start by saying thank you for making the plug-in makes life very easy to link multiple verses at a time.

There is one thing I was wondering about and needed guidance on, I am bilingual, and I have a vault that has the French bible, but I have found it difficult to link French scriptures, Are there any settings, I have to do to make sure the plugin know what I am talking about?

Thank you. I am looking forward hearing back from you

**Comment by SimonZindo** [comment]
Is it okay, if I make a video demonstrating the issue?

**Comment by kuchejak** [comment]
Sure, no problem
