### ISSUE TITLE
Linking multiple verses from a chapter

### ISSUE THREAD

**Issue by dubefab** [kuchejak/obsidian-bible-linker-plugin#40]
Hi, linking many verses that are together is easy, but is there a way to link to for example: Mat 6:1-3,6 ?
If not, can you implement? thanks!

**Comment by kuchejak** [comment]
Hi, this was already suggested in #22, so I'm closing this issue. Just to recap - this feature would be quite difficult to implement, but maybe one day I'll add it. As of right now I don't see it as a priority, but it would certainly be nice to have.
