### ISSUE TITLE
Aliases for different book names

### ISSUE THREAD

**Issue by sweenu** [kuchejak/obsidian-bible-linker-plugin#41]
My Bible is in French, but I have frontmatter aliases to each book's name. So, for example, my `Matthieu 1` note has a frontmatter alias `Matthew 1`.
That allows me to write my references in English when I take my notes in English while linking to the French Bible.
Would it be possible for this plugin to take those aliases into consideration?

**Comment by kuchejak** [comment]
Hello, as of right now I don't plan to add support for aliases, but you can use the input/output converters in the newest version (1.5.1) to accomplish the desired behaviour.
