### ISSUE TITLE
Cursor position after copy is before not after the citation

### ISSUE THREAD

**Issue by lexiconwriter** [kuchejak/obsidian-bible-linker-plugin#43]
Hi, is there a way to set the cursor position behind a citation? I use the linker very often - thank you for this great study improvement. All the time I pasted the bible verses into my text I have to click at the end to continue. Can you provide an automativ way for that use case?

**Comment by kuchejak** [comment]
Hello, as of right now this is not possible, but I'll try to implement it (hopefully soon)

**Comment by kuchejak** [comment]
It should now be fixed (version 1.5.2)

**Comment by lexiconwriter** [comment]
> It should now be fixed (version 1.5.2)

Thank you. Basically it works, e.g. for Mat 9:1. But trying to enter e.g. Mat 10:1 will not work.
