### ISSUE TITLE
With implementation of #43 the input of 2-digit chapters fails

### ISSUE THREAD

**Issue by lexiconwriter** [kuchejak/obsidian-bible-linker-plugin#44]
#43 works now. Unfortunately the input of two digit numbers in the "Insert reference" dialog doesn't work anymore. E.g. "Mat 10:1" fails with "File Mat 10 not found".

**Comment by kuchejak** [comment]
Thank you for the bug report, it’s probably caused by another change I have made today. I'll try to fix it tomorrow.

**Comment by lexiconwriter** [comment]
yes, it's working now! Thank you very much!
