### ISSUE TITLE
The plugin stopped working after the new update

### ISSUE THREAD

**Issue by dannuen** [kuchejak/obsidian-bible-linker-plugin#45]
Hi for some unknown reason, the plugin stopped working after the new update.
(Screenshot included): As you can see in the screenshot, I had everything set up but it doesn't return the verse.

![Screenshot 2024-06-06 230402](https://github.com/kuchejak/obsidian-bible-linker-plugin/assets/111210530/5ef0439f-551a-4490-b46f-4c680d211741)

I did try to install the previous version and it works perfectly.

**Comment by kuchejak** [comment]
Thanks for reporting. I'll try to fix the problem as soon as possible. 

Just to make sure, this is version 1.5.3?

**Comment by dannuen** [comment]
Yes, it is the 1.5.3 version. The version 1.5.0 is working for me.

**Comment by dannuen** [comment]
> Also you can try to input "sa 1,1" instead, that may work.

I did try that, and it didn't work.

**Comment by dannuen** [comment]
Thank you so much!
God bless you.
