### ISSUE TITLE
Enhancing embedded verses 

### ISSUE THREAD

**Issue by didpeugeot** [kuchejak/obsidian-bible-linker-plugin#47]
Hello Jakub,

I love your plugin and use it daily in my Bible reading!!!! It has changed my interactions with Obsidian.

One feature I would love to see added is on the Link Bible Verses command, with the embedded link type value, would it be possible to add a link to the verse, just as is so well executed on the Copy and Link Bible verses command? That would be such a GAME CHANGER for me when inserting text... because the embedded allows to avoid the "_static copy_" paradigm where copied text remains unchanged, even if/when the original source text is modified later.. 

Having the option also to add a line prefix and postfix would be a huge bonus too.

Using this + current Copy & Link would cover a large portion of my Bible meditations. Thank you so much in advance!

**Comment by kuchejak** [comment]
Hi! I'm gald you enjoy using the plugin. 

I have two question regarding your request:
- Why exactly are you not satisfied with the "static copy" paradigm (as you have called it)? Do your Bible files change?
- What exactly do you mean by "add a link to the verse"? Embedded link is a link. 

I consider the Link Bible Verses command finished and as of right now I don't plan on adding new features to it. It is a simple tool for people who can not use the Copy command for some reason and I think that it works for that purpose. But if you can convince me that a new feature is needed or if I see more people asking for the same thing as you I might consider it.

**Comment by kuchejak** [comment]
Closing for no response
