### ISSUE TITLE
link preview includes all verses.

### ISSUE THREAD

**Issue by Saorsa32** [kuchejak/obsidian-bible-linker-plugin#49]
I was wondering if it would be possible to see all the versus linked instead of just the first and last one. I use the link a lot and I would like to be able to see all of the versus linked when I hover over the link. Is it possible to do this?

**Comment by kuchejak** [comment]
Hi, the plugin does not affect what is shown on hover in any way, it just creates the links. If you want to see all the verses, use the copy command.
