### ISSUE TITLE
Feature Request: Option to Adjust Font Size in the Popup Window

### ISSUE THREAD

**Issue by santiyounger** [kuchejak/obsidian-bible-linker-plugin#51]
Hey, thank you so much for this amazing plugin.

I'm really mind-blown by what an incredible job you did with it. It really is next level.

I'm using it with various translations (each in their folder) and it's working great.

I really enjoy using the `Bible linker copy and link Bible verse` popup window, it's incredibly useful.

I would love to know if it would be possible to add a setting in the plugin to make the font bigger by choosing pixel size or something like that, because I use that popup a lot to compare translations before I copy and insert it into my note, so easier readability with bigger font, would be great.

Thanks

**Comment by kuchejak** [comment]
Hi, I'm glad you enjoy using the plugin.

What you are describing should be possible using [Obsidian CSS Snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets).

Something like the following should work:
```css
.copy-preview {
  font-size: 20px;
}
```

Just set the `font-size` to your liking.

Hope it helps.

**Comment by santiyounger** [comment]
Hey thanks a lot for such as quick reply, yep that works well! 

Please keep up your great work!
