### ISSUE TITLE
Bible version output

### ISSUE THREAD

**Issue by kdave5** [kuchejak/obsidian-bible-linker-plugin#52]
I have edited the settings within bible-linker to get the perfect reference output when I use the "copy" function. The only thing I am missing is some way to include the version/translation along with the reference in my document.

For example:
`Genesis 1:1`
vs.
`Genesis 1:1 (NET)`
with NET changing dynamically depending on the version I picked.

I feel like I was close to figuring it out, but in the end I think some code may need to be updated. Even if I could somehow extract the /KJV/ or /NET/ part of the file paths where my bibles are located. I feel like {version} or {v} should be a possible variable to add in the "link postfix" option.

**Comment by kuchejak** [comment]
Hi, I have added the option to use "{t}" to get the name of the used translation. Update the plugin to version 1.5.8 to use it.

**Comment by kdave5** [comment]
For multiple verses, I am only able to do the following because it only
works in "each verse prefix".
[image: image.png]

I think it would probably be more helpful if I could use it in the "Link
postfix"

Thanks for your excellent work.

**Comment by kuchejak** [comment]
Ahh I see, that makes sense. It should now be possible to use it in the link postfix as well in version 1.5.9.

**Comment by kdave5** [comment]
Awesome dude
