### ISSUE TITLE
Line prefix being added to invisible links

### ISSUE THREAD

**Issue by der-bingle** [kuchejak/obsidian-bible-linker-plugin#53]
A new issue has popped up for me since upgrading to 1.5.10.

I use a callout for scripture, so my line prefix is `> [!scripture] `. Previously, copy & link would result in... 

```
> [!scripture] [[Bible/CSB/John/John 1#1|John 1:1-2]]
In the beginning was the Word, and the Word was with God, and the Word was God. He was with God in the beginning. [[Bible/CSB/John/John 1#2|]]
```

But now the result is...

```
> [!scripture] [[Bible/CSB/John/John 1#1|John 1:1-2]]
In the beginning was the Word, and the Word was with God, and the Word was God. He was with God in the beginning. 
> [!scripture] [[Bible/CSB/John/John 1#1|]][[Bible/CSB/John/John 1#2|]]
```

I've looked through/changed settings, but haven't found a solution (except to not including invisible links, but I'd like to keep them if possible). Thanks!

**Comment by kuchejak** [comment]
Hi, should be fixed in 1.5.11 (you can update now).
