### ISSUE TITLE
Using pericope titles shifts the verses

### ISSUE THREAD

**Issue by Cattamer** [kuchejak/obsidian-bible-linker-plugin#54]
I use pericope titles in my source bible (Heading ###), the verses are marked with ##### v{n}.
In settings I set 'Verse offset' to -1 and 'Verse heading level' to #####

Depending on the chapter (and how many periscope titles there are) the verses shifts backwards.
It seems that Verse offset should fix this, cemented in with Verse heading level. Somehow it is not working properly.

It would be nice to keep the periscope titles.

**Comment by kuchejak** [comment]
Hi, that's strange. Your setup sounds correct, and I tested it myself without any issues.

Could you please provide at least two files that behave differently?

**Comment by Cattamer** [comment]
Hm, it looks like the periscopes have 2 Heading levels, H4 and H3.
It would be nice when only the selected Verse Heading Level's are used. Or that you can select multiple Headings to ignore.

**Comment by kuchejak** [comment]
Can you please provide at least two files that behave differently, as I have asked for?

Also are you using the copy command or the link command?

**Comment by Cattamer** [comment]
Apparently I had some minor copy/paste errors which were breaking the layout. Issues resolved. Thanks for this wonderful plugin.
