### ISSUE TITLE
When a verse contains multiple lines, only the first line is copied but not the ones after

### ISSUE THREAD

**Issue by AngelusDomini** [kuchejak/obsidian-bible-linker-plugin#9]
Not sure if I'm the only one having this issue, but when using the Copy Bible verses command for books or verses with line breaks for each verse (particularly, verses with poetic structure like in the Psalms), only the first line of the verse gets copied, and it proceeds to the next verse with the verse before that being incomplete. Here's an example:

>[[Ps. 23#1|Ps. 23,1-6]] The Lord is my shepherd, I shall not want;    he makes me lie down in green pastures.    he restores my soul. Even though I walk through the valley of the shadow of death, Thou preparest a table before me Surely goodness and mercy shall follow me [[Ps. 23#1|]][[Ps. 23#2|]][[Ps. 23#3|]][[Ps. 23#4|]][[Ps. 23#5|]][[Ps. 23#6|]]

or

>[[Ps. 23#1|Ps. 23,1-6]] 
>The Lord is my shepherd, I shall not want;
>   he makes me lie down in green pastures.
>   he restores my soul.
>Even though I walk through the valley of the shadow of death,
>Thou preparest a table before me
>Surely goodness and mercy shall follow me[[Ps. 23#1|]][[Ps. 23#2|]][[Ps. 23#3|]][[Ps. 23#4|]][[Ps. 23#5|]][[Ps. 23#6|]]

I'm copying all six verses of Psalm 23, but it's missing a lot of parts: Psalm 23:1 only contains one line, so it's complete; but Psalm 23:2 has two lines, but only the first lines gets copied and then the plugin copies the 3rd verse while ignoring the second line of the 2nd verse.

Am I missing something from the settings that can fix this issue, or is this an actual bug?
Appreciate your response and everything you're already doing with this plugin!

**Comment by kuchejak** [comment]
Hi, 
line breaks in verses are not supported as of right now, but I think that adding support for them should be (hopefully) relatively easy. I just have a very busy schedule now, so it may take a while (but probably not more than two weeks).

Could you please send me one of your bible files (with the line breaks)? Thank you

**Comment by AngelusDomini** [comment]
[Ps. 23.md](https://github.com/kuchejak/obsidian-bible-linker-plugin/files/8628745/Ps.23.md)

Here you go @kuchejak and thank you so much for the quick response. Will also be praying for you with regard to your busy schedule if you don't mind 😉

**Comment by kuchejak** [comment]
Hi, multiline verses should be now working (version 1.2.4). If you want them to be copied to separate lines, set _Put each verse on a new line?_ to true, otherwise multiline verses will be merged into one line.
